**Look into:**
* cointegration
* ratios between 2 stock prices (pairs)
* hurst exponent
* half life of mean reversion
* kalman filters
* augmented dickey fuller test
\
**research quantopian lectures
integrating seperate datasets?
Limiting by standard deveations
dimensionality reduction**

## Scientific Workflow ##
* Data: create a table with all stocks, lags for 3 days, and mentions(if avaliable).  List assumptions of the data
* EDA:  Correlation, 
* Hypothesis: Nothing predicts the stock price, something predicts the stock price
* model using logistic regression
* evaluate model fit

In [47]:
import pandas as pd
%pylab inline
import pandas_datareader.data as web
import datetime
from datetime import timedelta
import seaborn as sns
from statsmodels.graphics.tsaplots import plot_pacf
from statsmodels.graphics.tsaplots import plot_acf
from sqlalchemy import create_engine
import pandas as pd
import pandas_datareader.data as web
%load_ext sql
engine = create_engine('postgresql://localhost:5432/kylesdb')

plt.rcParams['figure.figsize'] = (14, 8)

Tesla = pd.read_sql("select * from tesla", engine)
Tesla.rename(index=str, columns={'Date':"TEdate", 'Open': 'TEopen', 'High':'TEhigh', 'Low':'TElow','Close':'TEclose', 'Volume':'TEvol'}, inplace=True)
GM = pd.read_sql("select * from \"GM\"", engine)
GM.rename(index=str, columns={'Date':"GMdate", 'Open': 'GMopen', 'High':'GMhigh', 'Low':'GMlow','Close':'GMclose', 'Volume':'GMvol'}, inplace=True)
Ford = pd.read_sql("select * from \"ford\"", engine)
Ford.rename(index=str, columns={'Date':"Fdate", 'Open': 'Fopen', 'High':'Fhigh', 'Low':'Flow','Close':'Fclose', 'Volume':'Fvol'}, inplace=True)
Daimler = pd.read_sql("select * from \"daimler\"", engine)
Daimler.rename(index=str, columns={'Date':"Ddate", 'Open': 'Dopen', 'High':'Dhigh', 'Low':'Dlow','Close':'Dclose', 'Volume':'Dvol'}, inplace=True)
Toyota = pd.read_sql("select * from \"toyota\"", engine)
Toyota.rename(index=str, columns={'Date':"TOdate", 'Open': 'TOopen', 'High':'TOhigh', 'Low':'TOlow','Close':'TOclose', 'Volume':'TOvol'}, inplace=True)
Solar = pd.read_sql("select * from \"solar\"", engine)
Solar.rename(index=str, columns={'Date':"Sdate", 'Open': 'Sopen', 'High':'Shigh', 'Low':'Slow','Close':'Sclose', 'Volume':'Svol'}, inplace=True)
SP_500 = pd.read_sql("select * from \"sp_500\"", engine)
SP_500.rename(index=str, columns={'Date':"SPdate", 'Open': 'SPopen', 'High':'SPhigh', 'Low':'SPlow','Close':'SPclose', 'Volume':'SPvol', 'Adj Close': 'SPadj_clo' }, inplace=True)
Nasdaq = pd.read_sql("select * from \"nasdaq\"", engine)
Nasdaq.rename(index=str, columns={'Date':"NQdate", 'Open': 'NQopen', 'High':'NQhigh', 'Low':'NQlow','Close':'NQclose', 'Volume':'NQvol', 'Adj Close': 'NQadj_clo' }, inplace=True)
Nasdaq.drop('NQadj_clo', axis=1, inplace=True)
SP_500.drop('SPadj_clo', axis=1, inplace=True)

Populating the interactive namespace from numpy and matplotlib
The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [48]:
a=pd.merge(SP_500, Nasdaq, right_index=True, left_index=True)
b=pd.merge(Solar,a,right_index=True, left_index=True)
c=pd.merge(Toyota,b,right_index=True, left_index=True)
d=pd.merge(Daimler,c,right_index=True, left_index=True)
e=pd.merge(Ford,d,right_index=True, left_index=True)
f=pd.merge(GM,e,right_index=True, left_index=True)
master=pd.merge(Tesla,f,right_index=True, left_index=True)

In [49]:
master

,TEdate,TEopen,TEhigh,TElow,TEclose,TEvol,GMdate,GMopen,GMhigh,GMlow,...,SPhigh,SPlow,SPclose,SPvol,NQdate,NQopen,NQhigh,NQlow,NQclose,NQvol
0,2015-01-02 00:00:00-05:00,222.87,223.25,213.26,219.31,4764443,2015-01-02 00:00:00-05:00,35.27,35.31,34.41,...,2072.360107,2046.040039,2058.199951,2708700000,2015-01-02 00:00:00-05:00,4760.240234,4777.009766,4698.109863,4726.810059,1435150000
1,2015-01-05 00:00:00-05:00,214.55,216.50,207.16,210.09,5368477,2015-01-05 00:00:00-05:00,34.98,35.25,34.07,...,2054.439941,2017.339966,2020.579956,3799120000,2015-01-05 00:00:00-05:00,4700.339844,4702.770020,4641.459961,4652.569824,1794470000
2,2015-01-06 00:00:00-05:00,210.06,214.20,204.21,211.28,6261936,2015-01-06 00:00:00-05:00,34.41,35.22,34.10,...,2030.250000,1992.439941,2002.609985,4460110000,2015-01-06 00:00:00-05:00,4666.850098,4667.330078,4567.589844,4592.740234,2167320000
3,2015-01-07 00:00:00-05:00,213.35,214.78,209.78,210.95,2968390,2015-01-07 00:00:00-05:00,35.23,35.95,35.04,...,2029.609985,2005.550049,2025.900024,3805480000,2015-01-07 00:00:00-05:00,4626.839844,4652.720215,4613.899902,4650.470215,1957950000
4,2015-01-08 00:00:00-05:00,212.81,213.80,210.01,210.62,3442509,2015-01-08 00:00:00-05:00,36.06,36.45,35.80,...,2064.080078,2030.609985,2062.139893,3934010000,2015-01-08 00:00:00-05:00,4689.540039,4741.379883,4688.020020,4736.189941,2105450000
5,2015-01-09 00:00:00-05:00,208.92,209.98,204.96,206.66,4668295,2015-01-09 00:00:00-05:00,36.21,36.37,35.41,...,2064.429932,2038.329956,2044.810059,3364140000,2015-01-09 00:00:00-05:00,4744.470215,4744.709961,4681.240234,4704.069824,1715830000
6,2015-01-12 00:00:00-05:00,203.05,204.47,199.25,202.21,5950280,2015-01-12 00:00:00-05:00,35.81,35.94,35.47,...,2049.300049,2022.579956,2028.260010,3456460000,2015-01-12 00:00:00-05:00,4714.069824,4715.810059,4650.649902,4664.709961,1861960000
7,2015-01-13 00:00:00-05:00,203.32,207.61,200.91,204.25,4477320,2015-01-13 00:00:00-05:00,36.08,36.40,34.68,...,2056.929932,2008.250000,2023.030029,4107300000,2015-01-13 00:00:00-05:00,4708.740234,4751.339844,4624.279785,4661.500000,2162180000
8,2015-01-14 00:00:00-05:00,185.83,195.20,185.00,192.69,11551855,2015-01-14 00:00:00-05:00,34.36,34.57,33.59,...,2018.400024,1988.439941,2011.270020,4378680000,2015-01-14 00:00:00-05:00,4610.759766,4655.370117,4595.979980,4639.319824,2073810000
9,2015-01-15 00:00:00-05:00,194.49,195.75,190.00,191.87,5216524,2015-01-15 00:00:00-05:00,34.78,34.87,33.38,...,2021.349976,1991.469971,1992.670044,4276720000,2015-01-15 00:00:00-05:00,4657.459961,4663.959961,4567.390137,4570.819824,1976260000
10,2015-01-16 00:00:00-05:00,190.70,194.49,189.65,193.07,3603158,2015-01-16 00:00:00-05:00,33.31,33.79,33.27,...,2020.459961,1988.119995,2019.420044,4056410000,2015-01-16 00:00:00-05:00,4566.379883,4635.819824,4563.109863,4634.379883,1970520000
11,2015-01-20 00:00:00-05:00,193.87,194.12,187.04,191.93,4503182,2015-01-20 00:00:00-05:00,33.90,34.01,33.35,...,2028.939941,2004.489990,2022.550049,3944340000,2015-01-20 00:00:00-05:00,4655.839844,4665.649902,4601.100098,4654.850098,1835040000
12,2015-01-21 00:00:00-05:00,189.55,198.68,189.51,196.57,4153043,2015-01-21 00:00:00-05:00,33.82,34.12,33.52,...,2038.290039,2012.040039,2032.119995,3730070000,2015-01-21 00:00:00-05:00,4641.950195,4692.459961,4629.589844,4667.419922,1847420000
13,2015-01-22 00:00:00-05:00,197.00,203.24,195.20,201.62,4116905,2015-01-22 00:00:00-05:00,34.15,34.18,33.31,...,2064.620117,2026.380005,2063.149902,4176050000,2015-01-22 00:00:00-05:00,4690.930176,4752.600098,4644.569824,4750.399902,1996550000
14,2015-01-23 00:00:00-05:00,200.29,203.50,198.33,201.29,3442371,2015-01-23 00:00:00-05:00,33.90,34.18,33.71,...,2062.979980,2050.540039,2051.820068,3573560000,2015-01-23 00:00:00-05:00,4748.189941,4771.180176,4737.950195,4757.879883,1653830000
15,2015-01-26 00:00:00-05:00,201.83,208.62,201.05,206.55,3234522,2015-01-26 00:00:00-05:00,33.71,34.04,33.60,...,2057.620117,2040.969971,2057.090088,3465760000,2015-01-26 00:00:00-05:00,4752.359863,4774.180176,4734.200195,4771.759766,1717510000
16,2015-01-27 00:00:00-05:00,204.42,208.03,203.30,205.98,2781024,2015-01-27 00:00:00-05:00,33.40,33.69,33.15,...,2047.859985,2019.910034,2029.550049,3329810000,2015-01-27 00:00:00-05:00,4698.229980,4721.870117,4659.830078,4681.500000,1954160000
17,2015-01-28 00:00:00-05:00,206.11,206.37,198.42,199.37,3149606,2015-01-28 00:00:00-05:00,33.51,33.57,32.75,...,2042.489990,2001.489990,2002.160034,4067530000,2015-01-28 00:00:00-05:00,4740.689941,4742.060059,4637.479980,4637.990234,2118680000
18,2015-01-29 00:00:00-05:00,201.07,205.98,196.50,205.20,3548106,2015-01-29 00:00:00-05:00,32.91,33.34,32.36,...,2024.640015,1989.180054,2021.250000,4127140000,2015-01-29 00:00:00-05:00,4635.729980,4688.410156,4601.759766,4683.410156,2110710000
19,2015-01-30 00:00:00-05:00,203.96,207.47,203.00,203.60,3006959,2015-01-30 00:00:00-05:00,32.88,33.15,32.62,...,2023.319946,1993.380005,1994.989990,4538650000,2015-01-30 00:00:00-05:00,4671.209961,4703.810059,4631.100098,4635.240234,2264230000
20,2015-02-02 00:00:00-05:00,203.97,211.95,203.30,210.94,4149186,2015-02-02 00:00:00-05:00,32.67,33.15,32.44,...,2021.660034,1980.900024,2020.849976,4008330000,2015-02-02 00:00:00-05:00,4650.600098,4676.689941,4580.459961,4676.689941,2006450000
21,2015-02-03 00:00:00-05:00,213.22,220.37,211.27,218.36,4826244,2015-02-03 00:00:00-05:00,33.50,34.20,33.44,...,2050.300049,2022.709961,2050.030029,4615900000,2015-02-03 00:00:00-05:00,4693.250000,4727.740234,4670.819824,4727.740234,2153520000
22,2015-02-04 00:00:00-05:00,218.29,221.48,216.80,218.55,3305377,2015-02-04 00:00:00-05:00,35.27,35.98,34.15,...,2054.739990,2036.719971,2041.510010,4141920000,2015-02-04 00:00:00-05:00,4699.810059,4744.330078,4697.790039,4716.700195,2212960000
23,2015-02-05 00:00:00-05:00,219.88,225.48,219.64,220.99,3522947,2015-02-05 00:00:00-05:00,36.28,36.60,36.01,...,2063.550049,2043.449951,2062.520020,3821990000,2015-02-05 00:00:00-05:00,4729.649902,4767.379883,4722.799805,4765.100098,2036590000
24,2015-02-06 00:00:00-05:00,222.00,223.40,216.50,217.36,3243931,2015-02-06 00:00:00-05:00,36.26,36.54,35.92,...,2072.399902,2049.969971,2055.469971,4232970000,2015-02-06 00:00:00-05:00,4768.839844,4787.180176,4731.220215,4744.399902,2034060000
25,2015-02-09 00:00:00-05:00,215.38,217.93,211.99,217.48,3472423,2015-02-09 00:00:00-05:00,35.79,36.10,35.51,...,2056.159912,2041.880005,2046.739990,3549540000,2015-02-09 00:00:00-05:00,4723.729980,4749.470215,4719.609863,4726.009766,1654680000
26,2015-02-10 00:00:00-05:00,217.55,220.50,215.00,216.29,5390542,2015-02-10 00:00:00-05:00,37.28,37.55,36.40,...,2070.860107,2048.620117,2068.590088,3669850000,2015-02-10 00:00:00-05:00,4754.629883,4793.270020,4737.120117,4787.640137,1773730000
27,2015-02-11 00:00:00-05:00,212.21,214.74,207.28,212.80,9769102,2015-02-11 00:00:00-05:00,37.51,37.86,37.28,...,2073.479980,2057.989990,2068.530029,3596860000,2015-02-11 00:00:00-05:00,4788.370117,4810.359863,4780.129883,4801.180176,1793630000
28,2015-02-12 00:00:00-05:00,193.57,203.09,193.28,202.88,15649607,2015-02-12 00:00:00-05:00,37.85,38.18,37.73,...,2088.530029,2069.979980,2088.479980,3788350000,2015-02-12 00:00:00-05:00,4828.080078,4857.609863,4823.569824,4857.609863,2075470000
29,2015-02-13 00:00:00-05:00,202.90,205.99,200.91,203.77,6191003,2015-02-13 00:00:00-05:00,37.93,38.07,37.35,...,2097.030029,2086.699951,2096.989990,3527450000,2015-02-13 00:00:00-05:00,4869.729980,4893.839844,4860.120117,4893.839844,1942240000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,2016-08-24 00:00:00-04:00,227.05,227.15,222.22,222.62,2570693,2016-08-24 00:00:00-04:00,31.84,32.09,31.76,...,2186.659912,2171.250000,2175.439941,3148280000,2016-08-24 00:00:00-04:00,5254.419922,5262.990234,5205.640137,5217.689941,1714780000
415,2016-08-25 00:00:00-04:00,223.11,223.80,220.77,220.96,1762519,2016-08-25 00:00:00-04:00,31.71,31.75,31.36,...,2179.000000,2169.739990,2172.469971,2969310000,2016-08-25 00:00:00-04:00,5207.609863,5230.589844,5201.640137,5212.200195,1511890000
416,2016-08-26 00:00:00-04:00,222.14,222.86,218.82,219.99,2238992,2016-08-26 00:00:00-04:00,31.67,31.82,31.42,...,2187.939941,2160.389893,2169.040039,3342340000,2016-08-26 00:00:00-04:00,5219.049805,5253.390137,5191.859863,5218.919922,1591060000
417,2016-08-29 00:00:00-04:00,220.15,220.40,215.00,215.20,3266334,2016-08-29 00:00:00-04:00,31.78,31.96,31.57,...,2183.479980,2170.189941,2180.379883,2654780000,2016-08-29 00:00:00-04:00,5223.799805,5245.120117,5222.339844,5232.330078,1416640000
418,2016-08-30 00:00:00-04:00,216.11,216.11,210.52,211.34,3168862,2016-08-30 00:00:00-04:00,31.67,32.00,31.23,...,2182.270020,2170.409912,2176.120117,3006800000,2016-08-30 00:00:00-04:00,5229.879883,5241.620117,5205.609863,5222.990234,1561020000
419,2016-08-31 00:00:00-04:00,210.43,212.60,208.65,212.01,3276548,2016-08-31 00:00:00-04:00,31.67,31.94,31.65,...,2173.790039,2161.350098,2170.949951,3766390000,2016-08-31 00:00:00-04:00,5216.419922,5219.890137,5191.180176,5213.220215,1761770000
420,2016-09-01 00:00:00-04:00,209.01,211.10,200.50,200.77,7943138,2016-09-01 00:00:00-04:00,31.86,32.55,31.34,...,2173.560059,2157.090088,2170.860107,3392120000,2016-09-01 00:00:00-04:00,5218.279785,5229.939941,5189.359863,5227.209961,1592520000
421,2016-09-02 00:00:00-04:00,202.33,203.20,196.20,197.78,5977413,2016-09-02 00:00:00-04:00,31.88,32.20,31.85,...,2184.870117,2173.590088,2179.979980,3091120000,2016-09-02 00:00:00-04:00,5249.660156,5263.390137,5231.020020,5249.899902,1474200000
422,2016-09-06 00:00:00-04:00,199.02,203.25,199.00,202.83,4390572,2016-09-06 00:00:00-04:00,32.25,32.34,31.85,...,2186.570068,2175.100098,2186.479980,3447650000,2016-09-06 00:00:00-04:00,5260.000000,5275.910156,5244.000000,5275.910156,1777940000
423,2016-09-07 00:00:00-04:00,205.50,206.50,200.71,201.71,3640923,2016-09-07 00:00:00-04:00,31.99,31.99,31.62,...,2187.870117,2179.070068,2186.159912,3319420000,2016-09-07 00:00:00-04:00,5274.229980,5287.609863,5261.919922,5283.930176,1878460000
424,2016-09-08 00:00:00-04:00,199.55,199.89,196.36,197.36,3377946,2016-09-08 00:00:00-04:00,31.85,32.00,31.68,...,2184.939941,2177.489990,2181.300049,3727840000,2016-09-08 00:00:00-04:00,5269.959961,5271.009766,5248.410156,5259.479980,1839790000
425,2016-09-09 00:00:00-04:00,199.09,199.92,193.70,194.47,3756992,2016-09-09 00:00:00-04:00,31.44,31.56,30.37,...,2169.080078,2127.810059,2127.810059,4233960000,2016-09-09 00:00:00-04:00,5217.950195,5225.930176,5125.910156,5125.910156,2208690000
426,2016-09-12 00:00:00-04:00,195.00,201.37,194.10,198.30,3715161,2016-09-12 00:00:00-04:00,30.36,31.35,30.13,...,2163.300049,2119.120117,2159.040039,4010480000,2016-09-12 00:00:00-04:00,5098.029785,5217.879883,5097.799805,5211.890137,2007610000
427,2016-09-13 00:00:00-04:00,197.06,198.49,193.45,196.05,3589379,2016-09-13 00:00:00-04:00,31.02,31.15,30.82,...,2150.469971,2120.270020,2127.020020,4141670000,2016-09-13 00:00:00-04:00,5181.140137,5195.029785,5131.270020,5155.250000,2071460000
428,2016-09-14 00:00:00-04:00,195.75,197.92,194.86,196.41,2259231,2016-09-14 00:00:00-04:00,30.79,30.87,30.49,...,2141.330078,2119.899902,2125.770020,3664100000,2016-09-14 00:00:00-04:00,5160.209961,5201.339844,5159.549805,5173.770020,1902680000
429,2016-09-15 00:00:00-04:00,196.49,202.52,196.40,200.42,3085115,2016-09-15 00:00:00-04:00,30.75,31.23,30.74,...,2151.310059,2122.360107,2147.260010,3373720000,2016-09-15 00:00:00-04:00,5178.100098,5254.779785,5176.250000,5249.689941,1950940000
430,2016-09-16 00:00:00-04:00,200.42,205.70,199.00,205.40,3107808,2016-09-16 00:00:00-04:00,31.13,31.13,30.60,...,2146.479980,2131.199951,2139.159912,5014360000,2016-09-16 00:00:00-04:00,5238.709961,5248.600098,5218.970215,5244.569824,3013860000
431,2016-09-19 00:00:00-04:00,207.00,209.43,205.00,206.34,2299498,2016-09-19 00:00:00-04:00,31.90,32.08,31.66,...,2153.610107,2135.909912,2139.120117,3163000000,2016-09-19 00:00:00-04:00,5263.549805,5281.069824,5222.910156,5235.029785,1791120000
432,2016-09-20 00:00:00-04:00,206.85,207.75,203.91,204.64,2410488,2016-09-20 00:00:00-04:00,31.91,31.94,31.33,...,2150.800049,2139.169922,2139.760010,3140730000,2016-09-20 00:00:00-04:00,5256.189941,5265.180176,5235.419922,5241.350098,1695190000
433,2016-09-21 00:00:00-04:00,206.37,207.00,201.56,205.22,2633503,2016-09-21 00:00:00-04:00,31.72,32.16,31.72,...,2165.110107,2139.570068,2163.120117,3712090000,2016-09-21 00:00:00-04:00,5263.649902,5299.399902,5233.939941,5295.180176,1999690000
434,2016-09-22 00:00:00-04:00,206.40,207.28,203.00,206.43,2382902,2016-09-22 00:00:00-04:00,32.27,32.47,32.27,...,2179.989990,2170.939941,2177.179932,3552830000,2016-09-22 00:00:00-04:00,5323.259766,5342.879883,5320.930176,5339.520020,1852100000
435,2016-09-23 00:00:00-04:00,205.99,210.18,205.67,207.45,2905229,2016-09-23 00:00:00-04:00,32.10,32.37,32.05,...,2173.750000,2163.969971,2164.689941,3317190000,2016-09-23 00:00:00-04:00,5327.430176,5329.709961,5301.629883,5305.750000,1761330000
436,2016-09-26 00:00:00-04:00,206.50,211.00,206.50,208.99,2394358,2016-09-26 00:00:00-04:00,32.02,32.12,31.75,...,2158.540039,2145.040039,2146.100098,3216170000,2016-09-26 00:00:00-04:00,5275.729980,5282.270020,5254.959961,5257.490234,1669520000
437,2016-09-27 00:00:00-04:00,209.65,209.98,204.61,205.81,3373180,2016-09-27 00:00:00-04:00,31.77,31.96,31.54,...,2161.129883,2141.550049,2159.929932,3437770000,2016-09-27 00:00:00-04:00,5254.180176,5306.810059,5251.319824,5305.709961,1751060000
438,2016-09-28 00:00:00-04:00,207.51,208.25,205.26,206.27,2088374,2016-09-28 00:00:00-04:00,31.75,31.94,31.54,...,2172.399902,2151.790039,2171.370117,3891460000,2016-09-28 00:00:00-04:00,5312.729980,5320.620117,5284.839844,5318.549805,1785470000
439,2016-09-29 00:00:00-04:00,205.60,207.33,200.58,200.70,2727029,2016-09-29 00:00:00-04:00,31.77,31.96,31.45,...,2172.669922,2145.199951,2151.129883,4249220000,2016-09-29 00:00:00-04:00,5311.310059,5317.000000,5254.520020,5269.149902,1941170000
440,2016-09-30 00:00:00-04:00,202.21,204.98,199.55,204.03,2586273,2016-09-30 00:00:00-04:00,31.63,31.95,31.58,...,2175.300049,2156.510010,2168.270020,4173340000,2016-09-30 00:00:00-04:00,5288.870117,5325.879883,5277.879883,5312.000000,2059800000
441,2016-10-03 00:00:00-04:00,212.30,215.67,208.25,213.70,5999892,2016-10-03 00:00:00-04:00,31.64,32.24,31.61,...,2164.409912,2154.770020,2161.199951,3137550000,2016-10-03 00:00:00-04:00,5300.290039,5308.600098,5281.950195,5300.870117,1604060000
442,2016-10-04 00:00:00-04:00,213.10,213.32,208.82,211.41,3541481,2016-10-04 00:00:00-04:00,32.08,32.47,32.04,...,2165.459961,2144.010010,2150.489990,3750890000,2016-10-04 00:00:00-04:00,5313.490234,5323.600098,5271.700195,5289.660156,1708990000
443,2016-10-05 00:00:00-04:00,212.24,213.15,208.12,208.46,1877534,2016-10-05 00:00:00-04:00,32.31,32.78,32.23,...,2163.949951,2155.149902,2159.729980,3906550000,2016-10-05 00:00:00-04:00,5305.279785,5330.810059,5304.060059,5316.020020,1753340000

In [4]:
# Tesla['n_index']=range(0,len(Tesla))
# GM['n_index']=range(0,len(GM))
# Ford['n_index']=range(0,len(Ford))
# Daimler['n_index']=range(0,len(Daimler))
# Toyota['n_index']=range(0,len(Toyota))

In [5]:
Teline_coef = np.polyfit(Tesla.n_index,Tesla.Close,1)
Tepolynomial = np.poly1d(Teline_coef)
pyplot.plot(Tesla.index, Tepolynomial(Tesla.n_index))

AttributeError: 'DataFrame' object has no attribute 'n_index'

In [ ]:
Gline_coef = np.polyfit(GM.n_index,GM.Close,1)
Gpolynomial = np.poly1d(Gline_coef)
pyplot.plot(GM.index, Gpolynomial(GM.n_index))

In [ ]:
Fline_coef = np.polyfit(Ford.n_index,Ford.Close,1)
Fpolynomial = np.poly1d(Fline_coef)
pyplot.plot(Ford.index, Fpolynomial(Ford.n_index))

In [ ]:
Dline_coef = np.polyfit(Daimler.n_index,Daimler.Close,1)
Dpolynomial = np.poly1d(Dline_coef)
pyplot.plot(Daimler.index, Dpolynomial(Daimler.n_index))

In [ ]:
Tline_coef = np.polyfit(Toyota.n_index,Toyota.Close,1)
Tpolynomial = np.poly1d(Tline_coef)
pyplot.plot(Toyota.index, Tpolynomial(Toyota.n_index))

In [ ]:
Tesla.Close.plot(figsize=(20,15), legend=True, label='Tesla', colormap='jet', fontsize=20)
GM.Close.plot(legend=True, label='GM')
Ford.Close.plot(legend=True, label='Ford')
Daimler.Close.plot(legend=True, label='Daimler')
Toyota.Close.plot(legend=True, label='Toyota')
plt.plot(Tesla.index, Tepolynomial(Tesla.n_index))
plt.plot(GM.index, Gpolynomial(GM.n_index))
plt.plot(Ford.index, Fpolynomial(Ford.n_index))
plt.plot(Daimler.index, Dpolynomial(Daimler.n_index))
plt.plot(Toyota.index, Tpolynomial(Toyota.n_index))
plt.figtext(.3,.92,'Top_4_Auto_Manfaturers_&_Tesla',fontsize=30,)
savefig('Top_4_Auto_Manfaturers_&_Tesla.png')

In [ ]:
# Filter to tesla
tesladata = Tesla.Close

# Plot the sales over time
Tesla[['Close']].plot()
#
print Tesla.Close.autocorr(lag=1)
print Tesla.Close.autocorr(lag=2)

In [ ]:
from pandas.tools.plotting import autocorrelation_plot

autocorrelation_plot(Tesla.Close)

We have established that the data is non stationary, we need to make the data stationary first.

In [ ]:
plot_pacf(Tesla.Close, lags=50);

In [ ]:
T_mod= Tesla.Close.diff()
print T_mod

In [ ]:
plot_acf(T_mod[1:], lags=50);

In [ ]:
plot_pacf(T_mod[1:], lags=50);

ARIMA model

In [ ]:
from statsmodels.tsa.arima_model import ARIMA

model = ARIMA(Tesla.Close, (0, 1, 0)).fit()
model.summary()

In [ ]:
len(Tesla.Close)

model.plot_predict(400, 450);

In [ ]:
plot_acf(model.resid, lags=50);

AR model

In [ ]:
ARmodel = ARIMA(Tesla.Close, (1, 0, 0)).fit()
ARmodel.summary()

In [ ]:
ARmodel.plot_predict(422, 450);

In [ ]:
plot_acf(ARmodel.resid, lags=50);